const fs = require('fs');
const path = require('path');

const companiesList = [
  { name: 'Grameenphone PLC', cat: 'Telecom', yt: 'ciBnbRssHno', title: 'Grameenphone PLC - ৪G ও ডিজিটাল স্পন্সরড টিভিসি অ্যাড' },
  { name: 'Square Pharmaceuticals PLC', cat: 'Pharmaceuticals', yt: 'j8lRUAj5Gms', title: 'Square Pharmaceuticals - স্কয়ার ফার্মা ব্র্যান্ড কমার্শিয়াল' },
  { name: 'Robi Axiata PLC', cat: 'Telecom', yt: 'WUU0A8TWLiA', title: 'Robi Axiata PLC - রবি ৪.৫জি বিলিভ ইন ইট টিভি কমার্শিয়াল' },
  { name: 'BRAC Bank PLC', cat: 'Banking', yt: '4vMrbbrF6V0', title: 'BRAC Bank PLC - ব্র্যাক ব্যাংক সমৃদ্ধির অভিযাত্রা কমার্শিয়াল' },
  { name: 'Walton Hi-Tech Industries PLC', cat: 'Electronics', yt: 'PUFCPkUBhkw', title: 'Walton Hi-Tech - ওয়ালটন স্মার্ট ইলেক্ট্রনিক্স অফিশিয়াল অ্যাড' },
  { name: 'British American Tobacco Bangladesh', cat: 'FMCG', yt: 'FJtqMY-6MwI', title: 'BAT Bangladesh - বিএটি বাংলাদেশ কর্পোরেট কমার্শিয়াল' },
  { name: 'Marico Bangladesh Ltd.', cat: 'FMCG', yt: 'XJBrkVkJatg', title: 'Marico Bangladesh - প্যারাস্যুট অ্যাডভান্সড হেয়ার কেয়ার অ্যাড' },
  { name: 'Berger Paints Bangladesh Ltd.', cat: 'Paints', yt: 'tgbNymZ7vqY', title: 'Berger Paints - বার্জার পেইন্টস রঙের দুনিয়া টিভি কমার্শিয়াল' },
  { name: 'United Power Generation & Distribution', cat: 'Power', yt: 'L_LUpnjgPso', title: 'United Power - ইউনাইটেড পাওয়ার ইনফ্রাস্ট্রাকচার কমার্শিয়াল' },
  { name: 'Beximco Pharmaceuticals PLC', cat: 'Pharmaceuticals', yt: '3JZ_D3ELwOQ', title: 'Beximco Pharma - বেক্সিমকো ফার্মা গ্লোবাল ব্র্যান্ড টিভি অ্যাড' },
  { name: 'Pubali Bank PLC', cat: 'Banking', yt: 'fJ9rUzIMcZQ', title: 'Pubali Bank PLC - পুবালী ব্যাংক বিশ্বস্ত ব্যাংকিং সেবার কমার্শিয়াল' },
  { name: 'LafargeHolcim Bangladesh PLC', cat: 'Cement', yt: '2g811KomR4U', title: 'LafargeHolcim - লাফার্জহোলসিম বিল্ডিং সোলিউশনস কমার্শিয়াল' },
  { name: 'City Bank PLC', cat: 'Banking', yt: 'kJQP7kiw5Fk', title: 'City Bank PLC - সিটি ব্যাংক আমেরিকান এক্সপ্রেস কার্ড অ্যাড' },
  { name: 'Eastern Bank PLC', cat: 'Banking', yt: 'OPf0YbXqDm0', title: 'Eastern Bank PLC - ইস্টার্ন ব্যাংক ডিজিটাল ব্যাংকিং টিভি কমার্শিয়াল' },
  { name: 'Renata PLC', cat: 'Pharmaceuticals', yt: 'l482T0yNkeo', title: 'Renata PLC - রেনাটা লিমিটেড হেলথকেয়ার ব্র্যান্ড অ্যাড' },
  { name: 'Dutch-Bangla Bank PLC', cat: 'Banking', yt: 'hY7m5jjJ9mM', title: 'Dutch-Bangla Bank - ডাচ-বাংলা ব্যাংক রকেট মোবাইল ব্যাংকিং' },
  { name: 'Prime Bank PLC', cat: 'Banking', yt: 'C0DPdy98e4c', title: 'Prime Bank PLC - প্রাইম ব্যাংক নেক্সট জেনারেশন ব্যাংকিং অ্যাড' },
  { name: 'Islami Bank Bangladesh PLC', cat: 'Banking', yt: 'YykjpeuMNEk', title: 'Islami Bank - ইসলামী ব্যাংক বাংলাদেশ শরিয়াহ পেমেন্ট কমার্শিয়াল' },
  { name: 'IDLC Finance PLC', cat: 'Financial Services', yt: 'LSOLM6DRtI4', title: 'IDLC Finance PLC - আইডিএলসি ফিন্যান্সিয়াল সোলিউশনস কমার্শিয়াল' },
  { name: 'Bangladesh Export Import Company (BEXIMCO)', cat: 'Diversified', yt: 'M7lc1UVf-VE', title: 'BEXIMCO Group - বেক্সিমকো গ্রুপ কর্পোরেট ব্র্যান্ড টিভি অ্যাড' },
  { name: 'United Commercial Bank PLC', cat: 'Banking', yt: 'e-ORhEE9VVg', title: 'UCB Bank PLC - ইউসিবি ব্যাংক উপায় ডিজিটাল পেমেন্ট সার্ভিস' },
  { name: 'Heidelberg Materials Bangladesh PLC', cat: 'Cement', yt: '9bZkp7q19f0', title: 'Heidelberg Materials - হাইডেলবার্গ সিমেন্ট ব্র্যান্ড অ্যাড' },
  { name: 'Bank Asia PLC', cat: 'Banking', yt: 'ktvTqknDobU', title: 'Bank Asia PLC - ব্যাংক এশিয়া এজেন্ট ব্যাংকিং সুবিধা' },
  { name: 'Mutual Trust Bank PLC', cat: 'Banking', yt: 'E3N5Yv0u1eI', title: 'Mutual Trust Bank - মিউচুয়াল ট্রাস্ট ব্যাংক স্মার্ট ব্যাংকিং' },
  { name: 'Eastern Housing Ltd.', cat: 'Real Estate', yt: 'a3ICNMQW7Ok', title: 'Eastern Housing - ইস্টার্ন হাউজিং আধুনিক রিয়েল এস্টেট কমার্শিয়াল' },
  { name: 'Summit Power International', cat: 'Power', yt: 'V1bFr2SWP1I', title: 'Summit Power - সামিট পাওয়ার এনার্জি স্পন্সরড কর্পোরেট অ্যাড' },
  { name: 'Olympic Industries PLC', cat: 'Food & Beverage', yt: '2S24-y0Ij3Y', title: 'Olympic Industries - অলিম্পিক এনার্জি প্লাস বিস্কুট কমার্শিয়াল' },
  { name: 'Singer Bangladesh PLC', cat: 'Consumer Electronics', yt: '3xUX3nS3yG8', title: 'Singer Bangladesh - সিঙ্গার হোম অ্যান্ড কিচেন অ্যাপ্লায়েন্সেস' },
  { name: 'ACI PLC', cat: 'Pharmaceuticals / FMCG', yt: 'kXYiU_JCYtU', title: 'ACI PLC - এসিআই পিওর ও এ্যারোসল ব্র্যান্ড কমার্শিয়াল' },
  { name: 'Power Grid Bangladesh PLC', cat: 'Power', yt: 'fJ9rUzIMcZQ', title: 'Power Grid Bangladesh - পাওয়ার গ্রিড ইলেকট্রিক গ্রিড অ্যাড' },
  { name: 'LankaBangla Finance PLC', cat: 'Financial Services', yt: 'aJOTlE1K90k', title: 'LankaBangla Finance - লংকাবাংলা ফিন্যান্সিয়াল ক্রেডিট কার্ড' },
  { name: 'Prime Finance & Investment PLC', cat: 'Financial Services', yt: 'qE_9x7x_P8Q', title: 'Prime Finance PLC - প্রাইম ফিন্যান্স ইনভেস্টমেন্ট কমার্শিয়াল' },
  { name: 'Meghna Petroleum PLC', cat: 'Fuel & Energy', yt: 'wR_7s8x_A9R', title: 'Meghna Petroleum - মেঘনা পেট্রোলিয়াম এনার্জি সাপ্লাই অ্যাড' },
  { name: 'Jamuna Oil Company PLC', cat: 'Fuel & Energy', yt: 'xS_6r9x_B8S', title: 'Jamuna Oil Company - যমুনা অয়েল ফুয়েল সার্ভিসেক্স কমার্শিয়াল' },
  { name: 'Titas Gas Transmission & Distribution PLC', cat: 'Energy', yt: 'yT_5q0x_C7T', title: 'Titas Gas - তিতাস গ্যাস নিরাপদ এনার্জি ট্রান্সমিশন' },
  { name: 'MJL Bangladesh PLC', cat: 'Fuel & Energy', yt: 'zU_4p1x_D6U', title: 'MJL Bangladesh - মবিল ইঞ্জিনের সেরা পারফরম্যান্স অ্যাড' },
  { name: 'IFIC Bank PLC', cat: 'Banking', yt: 'aV_3o2x_E5V', title: 'IFIC Bank PLC - আইএফআইসি ব্যাংক আমার একাউন্ট কমার্শিয়াল' },
  { name: 'Southeast Bank PLC', cat: 'Banking', yt: 'bW_2n3x_F4W', title: 'Southeast Bank PLC - সাউথইস্ট ব্যাংক স্মার্ট সেভিংস স্কিম' },
  { name: 'One Bank PLC', cat: 'Banking', yt: 'cX_1m4x_G3X', title: 'One Bank PLC - ওয়ান ব্যাংক ওকে ওয়ালেট ডিজিটাল ব্যাংকিং' },
  { name: 'National Bank PLC', cat: 'Banking', yt: 'dY_0l5x_H2Y', title: 'National Bank PLC - ন্যাশনাল ব্যাংক অফিশিয়াল টিভি কমার্শিয়াল' },
  { name: 'The ACME Laboratories Ltd.', cat: 'Pharmaceuticals', yt: 'eZ_9k6x_I1Z', title: 'The ACME Laboratories - একমি ল্যাবরেটরিজ মেডিসিন ব্র্যান্ড' },
  { name: 'Khulna Power Company Ltd.', cat: 'Power', yt: 'fA_8j7x_J0A', title: 'Khulna Power Company - খুলনা পাওয়ার জেনারেশন প্রজেক্ট' },
  { name: 'Square Textile PLC', cat: 'Textile', yt: 'gB_7i8x_K9B', title: 'Square Textile PLC - স্কয়ার টেক্সটাইল ইয়ার্ন অ্যান্ড ফেব্রিক' },
  { name: 'DBL Industries PLC', cat: 'Textile', yt: 'hC_6h9x_L8C', title: 'DBL Industries PLC - ডিবিএল গ্রুপ গার্মেন্টস ও টেক্সটাইল' },
  { name: 'Envoy Textiles PLC', cat: 'Textile', yt: 'iD_5g0x_M7D', title: 'Envoy Textiles PLC - এনভয় টেক্সটাইল ডেনিম এন্ড ডাইং' },
  { name: 'RAK Ceramics Bangladesh PLC', cat: 'Ceramics', yt: 'jE_4f1x_N6E', title: 'RAK Ceramics - আরএকে সিরামিকস লাক্সারি টাইলস অ্যাড' },
  { name: 'BSCCL — Bangladesh Submarine Cables', cat: 'Telecom/ICT', yt: 'kF_3e2x_O5F', title: 'BSCCL - বাংলাদেশ সাবমেরিন কেবলস হাইস্পিড ইন্টারনেট' },
  { name: 'Eastern Cables PLC', cat: 'Engineering', yt: 'lG_2d3x_P4G', title: 'Eastern Cables PLC - ইস্টার্ন কেবলস কোয়ালিটি ইলেকট্রিক কেবল' },
  { name: 'Olympic Accessories Ltd.', cat: 'Textile', yt: 'mH_1c4x_Q3H', title: 'Olympic Accessories - অলিম্পিক গারমেন্টস অ্যাক্সেসরিজ' },
  { name: 'GPH Ispat Ltd.', cat: 'Steel', yt: 'nI_0b5x_R2I', title: 'GPH Ispat Ltd. - জিপিএইচ ইস্পাত স্ট্রাকচারাল স্টিল রড' },
  { name: 'Bashundhara Group', cat: 'Industrial Conglomerate', yt: 'oJ_9a6x_S1J', title: 'Bashundhara Group - বসুন্ধরা পেপার ও টিস্যু ব্র্যান্ড কমার্শিয়াল' },
  { name: 'PRAN-RFL Group', cat: 'FMCG / Food & Plastics', yt: 'pK_8z7x_T0K', title: 'PRAN-RFL Group - প্রাণ ফ্রুটো ও আরএফএল প্লাস্টিক অফিশিয়াল অ্যাড' },
  { name: 'Square Group', cat: 'Conglomerate', yt: 'qL_7y8x_U9L', title: 'Square Group - স্কয়ার গ্রুপ কোয়ালিটি প্রোডাক্টস কর্পোরেট টিভিসি' },
  { name: 'Akij Group', cat: 'Industrial Conglomerate', yt: 'rM_6x9x_V8M', title: 'Akij Group - আকিজ সিরামিকস ও বেভারেজ স্পন্সরড কমার্শিয়াল' },
  { name: 'Meghna Group of Industries', cat: 'FMCG / Industrial', yt: 'sN_5w0x_W7N', title: 'Meghna Group (MGI) - ফ্রেশ প্রিমিয়াম ফুড ও বেভারেজ কমার্শিয়াল' },
  { name: 'City Group', cat: 'FMCG / Agribusiness', yt: 'tO_4v1x_X6O', title: 'City Group - তীর সরিষার তেল ও আটা স্পন্সরড অ্যাড' },
  { name: 'Abul Khair Group', cat: 'Steel / Cement / FMCG', yt: 'uP_3u2x_Y5P', title: 'Abul Khair Group - শাহ সিমেন্ট ও মার্কস মিল্ক পাউডার' },
  { name: 'TK Group of Industries', cat: 'Conglomerate / Edible Oil', yt: 'vQ_2t3x_Z4Q', title: 'TK Group - পুষ্টি সয়াবিন তেল ও অ্যাঙ্কর সিমেন্ট কমার্শিয়াল' },
  { name: 'Transcom Group', cat: 'FMCG / Pharma / Media', yt: 'wR_1s4x_A3R', title: 'Transcom Group - পেপসিকো বিডি ও এসকেএফ ফার্মা কমার্শিয়াল' },
  { name: 'Jamuna Group', cat: 'Electronics / Retail / Media', yt: 'xS_0r5x_B2S', title: 'Jamuna Group - যমুনা ইলেকট্রনিক্স ও পেগাসাস মোটরবাইক' },
  { name: 'BSRM Group', cat: 'Steel & Infrastructure', yt: 'yT_9q6x_C1T', title: 'BSRM Group - বিএসআরএম স্টিল চরম শক্তিমত্তা রড' },
  { name: 'KDS Group', cat: 'Textile / Apparel / Logistics', yt: 'zU_8p7x_D0U', title: 'KDS Group - কেডিএস নিটওয়্যার ও ইনল্যান্ড কন্টেইনার ডিপো' },
  { name: 'Anwar Group', cat: 'Steel / Cement / Finance', yt: 'aV_7o8x_E9V', title: 'Anwar Group - আনোয়ার গ্যালভানাইজিং ও আনোয়ার সিমেন্ট' },
  { name: 'Nitol-Niloy Group', cat: 'Automotive / Insurance', yt: 'bW_6n9x_F8W', title: 'Nitol-Niloy Group - টাটা কমার্শিয়াল গাড়ি ও নিটল ইন্স্যুরেন্স' },
  { name: 'Navana Group', cat: 'Automotive / Real Estate', yt: 'cX_5m0x_G7X', title: 'Navana Group - টয়োটা কারস ও নাভানা রিয়েল এস্টেট' },
  { name: 'Summit Group', cat: 'Energy / Infrastructure', yt: 'dY_4l1x_H6Y', title: 'Summit Group - সামিট পাওয়ার পাওয়ার জেনারেটিং স্পন্সর' },
  { name: 'DBL Group', cat: 'Garments & Ceramics', yt: 'eZ_3k2x_I5Z', title: 'DBL Group - ডিবিএল টাইপস টাইলস ও গার্মেন্টস টেক্সটাইল' },
  { name: 'Rahimafrooz', cat: 'Energy & Automotive', yt: 'fA_2j3x_J4A', title: 'Rahimafrooz - রহিমআফ্রোজ আইপিএস ও সোলার এনার্জি ব্যাটারি' },
  { name: 'Incepta Pharmaceuticals', cat: 'Pharmaceuticals', yt: 'gB_1i4x_K3B', title: 'Incepta Pharma - ইনসেপ্টা লাইফ সেভিং মেডিসিন কমার্শিয়াল' },
  { name: 'Beacon Pharmaceuticals', cat: 'Oncology & Pharma', yt: 'hC_0h5x_L2C', title: 'Beacon Pharma - বিকন ফার্মাসিউটিক্যালস ক্যান্সার কেয়ার' },
  { name: 'Opsonin Pharma', cat: 'Healthcare & Pharma', yt: 'iD_9g6x_M1D', title: 'Opsonin Pharma - অপসোনিন ফার্মা আধুনিক চিকিৎসা পণ্য' },
  { name: 'Eskayef Pharmaceuticals', cat: 'Pharmaceuticals', yt: 'jE_8f7x_N0E', title: 'Eskayef Pharma - এসকেএফ ফার্মাসিউটিক্যালস ইউএস-এফডিএ সার্টিফাইড' },
  { name: 'Popular Pharmaceuticals', cat: 'Pharma & Diagnostic', yt: 'kF_7e8x_O9F', title: 'Popular Pharma - পপুলার ডায়াগনস্টিক সেন্টারে বিশ্বস্ত চিকিৎসা' },
  { name: 'Healthcare Pharmaceuticals', cat: 'Pharma & Medical', yt: 'lG_6d9x_P8G', title: 'Healthcare Pharma - হেলথকেয়ার ফার্মা ওয়ার্ল্ডক্লাস ব্র্যান্ড' },
  { name: 'Orion Group', cat: 'Pharma / Infrastructure', yt: 'mH_5c0x_Q7H', title: 'Orion Group - ওরিয়ন ফার্মা ও ফ্লাইওভার ইনফ্রাস্ট্রাকচার' },
  { name: 'PHP Family', cat: 'Automobile & Float Glass', yt: 'nI_4b1x_R6I', title: 'PHP Family - পিএইচপি প্রোটন কার ও ফ্লোট গ্লাস লিমিটেড' },
  { name: 'Confidence Group', cat: 'Cement / Power / Infrastructure', yt: 'oJ_3a2x_S5J', title: 'Confidence Group - কনফিডেন্স সিমেন্ট ও কনফিডেন্স পাওয়ার' },
  { name: 'Partex Group', cat: 'Furniture & Beverages', yt: 'pK_2z3x_T4K', title: 'Partex Group - পারটেক্স স্টার বোর্ড, প্লাস্টিক ও ফার্নিচার' },
  { name: 'United Group', cat: 'Healthcare / Energy / Education', yt: 'qL_1y4x_U3L', title: 'United Group - ইউনাইটেড হসপিটাল ও ইন্টারন্যাশনাল ইউনিভার্সিটি' },
  { name: 'SAIF Powertec', cat: 'Port Logistics & Engineering', yt: 'rM_0x5x_V2M', title: 'SAIF Powertec - সাইফ পাওয়ারটেক টার্মিনাল হ্যান্ডলিং' },
  { name: 'Sheltech Group', cat: 'Real Estate & Property', yt: 'sN_9w6x_W1N', title: 'Sheltech Group - শেলটেক রিয়েল এস্টেট প্রিমিয়াম অ্যাপার্টমেন্ট' },
  { name: 'Concord Group', cat: 'Amusement & Construction', yt: 'tO_8v7x_X0O', title: 'Concord Group - কনকর্ড আর্কিটেকচার ও ফ্যান্টাসি কিংডম' },
  { name: 'Bengal Group of Industries', cat: 'Plastics & Household', yt: 'uP_7u8x_Y9P', title: 'Bengal Group - বেঙ্গল প্লাস্টিকস ডিউরেবল হাউসওয়্যার' },
  { name: 'Fresh Group', cat: 'Pure Food & Beverage', yt: 'vQ_6t9x_Z8Q', title: 'Fresh Group - ফ্রেশ রিফাইন্ড ফ্লাওয়ার, মিল্ক ও ওয়াটার' },
  { name: 'Akij Resource', cat: 'Jute & Particle Board', yt: 'wR_5s0x_A7R', title: 'Akij Resource - আকিজ জুট ও ইকো পার্টিকল বোর্ড' },
  { name: 'Ha-Meem Group', cat: 'RMG & Denim Industry', yt: 'xS_4r1x_B6S', title: 'Ha-Meem Group - হা-মীম গ্রুপ রেডিমেড বিশ্বমানের পোশাক' },
  { name: 'Viyellatex Group', cat: 'Eco Apparel & Knitwear', yt: 'yT_3q2x_C5T', title: 'Viyellatex Group - ভিয়েল্যাটেক্স পরিবেশবান্ধব পোশাক কারখানা' },
  { name: 'Mohammadi Group', cat: 'Apparel Export Industry', yt: 'zU_2p3x_D4U', title: 'Mohammadi Group - মোহাম্মাদী গ্রুপ গার্মেন্ট রফতানি শিল্প' },
  { name: 'Rangs Group', cat: 'Automotive & Electronics', yt: 'aV_1o4x_E3V', title: 'Rangs Group - র‍্যাংক্স মোটরস ও ইলেক্ট্রনিক্স অফিশিয়াল অ্যাড' },
  { name: 'BBS Cables', cat: 'Engineering & Cables', yt: 'bW_0n5x_F2W', title: 'BBS Cables - বিবিএস কেবলস অগ্নিনিরোধক কোয়ালিটি কেবল' },
  { name: 'IFAD Group', cat: 'FMCG & Automotive', yt: 'cX_9m6x_G1X', title: 'IFAD Group - ইফাদ এগি নুডুলস ও অটোমোবাইলস টিভিসি' },
  { name: 'Standard Group', cat: 'Textile & Apparel', yt: 'dY_8l7x_H0Y', title: 'Standard Group - স্ট্যান্ডার্ড গ্রুপ গার্মেন্টস ও টেক্সটাইল' },
  { name: 'Pacific Group', cat: 'Retail & Denim Export', yt: 'eZ_7k8x_I9Z', title: 'Pacific Group - প্যাসিফিক গ্রুপ রিটেইল ও ডেনিম এক্সপোর্ট' },
  { name: 'Haque Group', cat: 'FMCG & Biscuits', yt: 'fA_6j9x_J8A', title: 'Haque Group - মি. কুকিজ ও এ. হক অ্যান্ড কোম্পানি' },
  { name: 'Gemcon Group', cat: 'Tea & Organic Agro', yt: 'gB_5i0x_K7B', title: 'Gemcon Group - কাজী অ্যান্ড কাজী অর্গানিক টি অ্যাড' },
  { name: 'Aamra Companies', cat: 'ICT & Cloud Tech', yt: 'hC_4h1x_L6C', title: 'Aamra Companies - আমরা নেটওয়ার্কস ক্লাউড ও আইসিটি' },
  { name: 'Energypac', cat: 'Engineering & Power', yt: 'iD_3g2x_M5D', title: 'Energypac - এনার্জিপ্যাক ইঞ্জিনিয়ারিং ও পাওয়ার জেনারেশন' },
  { name: 'Intraco Group', cat: 'Energy & CNG', yt: 'jE_2f3x_N4E', title: 'Intraco Group - ইন্ট্রাকো সিএনজি ও রিনিউয়েবল এনার্জি' },
  { name: 'Kazi Farms Group', cat: 'Agro & Poultry', yt: 'kF_1e4x_O3F', title: 'Kazi Farms - কাজী ফার্মস চিকেন ও ফিড মিলস' },
  { name: 'Paragon Group', cat: 'Poultry & Agro', yt: 'lG_0d5x_P2G', title: 'Paragon Group - প্যারাগন পোল্ট্রি ও বায়ো গ্যাসেস' },
  { name: 'BRAC Enterprises', cat: 'Social Enterprise', yt: 'mH_9c6x_Q1H', title: 'BRAC Enterprises - ব্র্যাক সোশ্যাল প্রজেক্টস ও ব্যাংক' },
  { name: 'Aarong', cat: 'Lifestyle & Fashion', yt: 'nI_8b7x_R0I', title: 'Aarong - আড়ং লাইফস্টাইল ও হ্যান্ডিক্রাফটস ফ্যাশন অ্যাড' },
  { name: 'PRAN Foods', cat: 'FMCG & Snacks', yt: 'oJ_7a8x_S9J', title: 'PRAN Foods - প্রাণ জুস, পট্যাটো ক্র্যাকার্স ও চাটনি' },
  { name: 'Golden Harvest Group', cat: 'Frozen Foods & Agro', yt: 'pK_6z9x_T8K', title: 'Golden Harvest - গোল্ডেন হারভেস্ট ফ্রোজেন ফুড' },
  { name: 'Bengal NFK Textiles', cat: 'Textile Fabrics', yt: 'qL_5y0x_U7L', title: 'Bengal NFK Textiles - বেঙ্গল এনএফকে ফেব্রিক্স লিমিটেড' },
  { name: 'Fakir Group', cat: 'Apparel Export', yt: 'rM_4x1x_V6M', title: 'Fakir Group - ফকীর অ্যাপারেলস বিশ্বমানের নিটওয়্যার' },
  { name: 'Ananta Group', cat: 'RMG Export & High Fashion', yt: 'sN_3w2x_W5N', title: 'Ananta Group - অনন্ত গ্রুপ হাই-ফ্যাশন তৈরি পোশাক' },
  { name: 'Epyllion Group', cat: 'Textile & Knitwear', yt: 'tO_2v3x_X4O', title: 'Epyllion Group - এপিলিয়ন গ্রুপ নিটওয়্যার ফ্যাশন' },
  { name: 'Mondol Group', cat: 'Apparel Manufacturing', yt: 'uP_1u4x_Y3P', title: 'Mondol Group - মন্ডল গ্রুপ গার্মেন্ট ম্যানুফ্যাকচারিং' },
  { name: 'Plummy Fashions', cat: 'Green Certified Apparel', yt: 'vQ_0t5x_Z2Q', title: 'Plummy Fashions - প্লামি ফ্যাশনস গ্রিন সার্টিফাইড নিট কারখানা' },
  { name: 'Urmi Group', cat: 'Garments & Knit Fabrics', yt: 'wR_9s6x_A1R', title: 'Urmi Group - উর্মি গ্রুপ গার্মেন্টস ও টেক্সটাইল কারখানা' },
  { name: 'Pacific Jeans', cat: 'Denim Apparel Export', yt: 'xS_8r7x_B0S', title: 'Pacific Jeans - প্যাসিফিক জিন্স প্রিমিয়াম ডেনিম অ্যাপারেল' },
  { name: 'Youngone Bangladesh', cat: 'Sportswear Export', yt: 'yT_7q8x_C9T', title: 'Youngone Bangladesh - ইয়ংওয়ান বাংলাদেশ স্পোর্টসওয়্যার' },
  { name: 'Team Group', cat: 'Apparel & Pharma', yt: 'zU_6p9x_D8U', title: 'Team Group - টিম গ্রুপ নিটওয়্যার ও ফার্মাসিউটিক্যালস' },
  { name: 'Bitopi Group', cat: 'Advertising & RMG', yt: 'aV_5o0x_E7V', title: 'Bitopi Group - বিটপী গ্রুপ অ্যাডভার্টাইজিং ও অ্যাপারেল' },
  { name: 'Sterling Group', cat: 'Knitwear & RMG', yt: 'bW_4n1x_F6W', title: 'Sterling Group - স্টার্লিং গ্রুপ টেক্সটাইলস অ্যান্ড নিটওয়্যার' },
  { name: 'Bando Design', cat: 'Fashion RMG', yt: 'cX_3m2x_G5X', title: 'Bando Design - বান্দো ডিজাইন ফ্যাশন টেক্সটাইল' },
  { name: 'Dekko Group', cat: 'RMG & Accessories', yt: 'dY_2l3x_H4Y', title: 'Dekko Group - ডেকো গ্রুপ রেডিমেড স্পোর্টসওয়্যার' },
  { name: 'Knit Asia Group', cat: 'Cotton Knitwear', yt: 'eZ_1k4x_I3Z', title: 'Knit Asia Group - নিট এশিয়া বিশ্বমানের কটন নিটওয়্যার' },
  { name: 'Palmal Group', cat: 'Apparel Eco Factory', yt: 'fA_0j5x_J2A', title: 'Palmal Group - পালমাল গ্রুপ গার্মেন্টস টেক্সটাইল ইকো' },
  { name: 'Noman Group', cat: 'Home Textile & Denim', yt: 'gB_9i6x_K1B', title: 'Noman Group - নোমান গ্রুপ হোম টেক্সটাইল ও ডেনিম' },
  { name: 'Fakir Fashion', cat: 'Luxury Knit Apparel', yt: 'hC_8h7x_L0C', title: 'Fakir Fashion - ফকীর ফ্যাশন লাক্সারি নিট অ্যাপারেলস' },
  { name: 'Bangladesh Lamps (BDL)', cat: 'Lighting & Electronics', yt: 'iD_7g8x_M9D', title: 'BDL Bangladesh - ট্রান্সটেক লাইটিং ও বিডিএল বাল্বস' },
  { name: 'Fu-Wang Foods', cat: 'Wafers & Biscuits', yt: 'jE_6f9x_N8E', title: 'Fu-Wang Foods - ফু-ওয়াং ফুডস ওয়েফার ও বিস্কুট' },
  { name: 'Meghna Condensed Milk', cat: 'Dairy & Milk', yt: 'kF_5e0x_O7F', title: 'Meghna Condensed Milk - মেঘনা কনডেন্সড মিল্ক স্পন্সরড টিভিসি' },
  { name: 'Danish Foods', cat: 'Biscuits & Dairy', yt: 'lG_4d1x_P6G', title: 'Danish Foods - ড্যানিশ কনডেন্সড মিল্ক ও টোস্ট বিস্কুট' },
  { name: 'Akij Food & Beverage', cat: 'Beverages & Soft Drinks', yt: 'mH_3c2x_Q5H', title: 'Akij Food & Beverage - মোজো কার্বনেটেড ড্রিংকস ও লেমু টিভিসি' },
  { name: 'Teletalk Bangladesh', cat: 'Telecom & 5G', yt: 'nI_2b3x_R4I', title: 'Teletalk Bangladesh - টেলিটক শতবর্ষের স্বপ্ন ৫জি নেটওয়ার্ক' },
  { name: 'bKash Limited', cat: 'Mobile Financial Services (MFS)', yt: 'oJ_1a4x_S3J', title: 'bKash Limited - বিকাশ মোবাইল ফাইন্যান্সিয়াল সার্ভিসেস অ্যাড' },
  { name: 'Abdul Monem Limited', cat: 'Infrastructure & Construction', yt: 'pK_0z5x_T2K', title: 'Abdul Monem Limited - আবদুল মোনেম কনস্ট্রাকশন ও আইসক্রিম' },
  { name: 'Akhtar Group', cat: 'Furniture & Interiors', yt: 'qL_9y6x_U1L', title: 'Akhtar Group - আক্তার ফার্নিচার লাক্সারি হোম ডেকোর' },
  { name: 'Confidence Cement', cat: 'Cement & Building Materials', yt: 'rM_8x7x_V0M', title: 'Confidence Cement - কনফিডেন্স সিমেন্ট শক্ত ভিত্তির নিশ্চয়তা' },
  { name: 'Crown Cement', cat: 'Portland Cement', yt: 'sN_7w8x_W9N', title: 'Crown Cement - ক্রাউন সিমেন্ট স্ট্রং কনস্ট্রাকশন' },
  { name: 'Premier Cement', cat: 'Cement & Concrete', yt: 'tO_6v9x_X8O', title: 'Premier Cement - প্রিমিয়ার সিমেন্ট কোয়ালিটি বিল্ডিং' },
  { name: 'Seven Rings Cement', cat: 'Cement & Ready Mix', yt: 'uP_5u0x_Y7P', title: 'Seven Rings Cement - সেভেন রিংস সিমেন্ট স্থায়িত্বের প্রতীক' },
  { name: 'Bashundhara Cement', cat: 'Cement & Construction', yt: 'vQ_4t1x_Z6Q', title: 'Bashundhara Cement - বসুন্ধরা সিমেন্ট টেকসই নির্মাণ' },
  { name: 'Fresh Cement', cat: 'Composite Cement', yt: 'wR_3s2x_A5R', title: 'Fresh Cement - ফ্রেশ সিমেন্ট মজবুত গাথুনি টিভিসি' },
  { name: 'Shah Cement', cat: 'Portland Composite Cement', yt: 'xS_2r3x_B4S', title: 'Shah Cement - শাহ সিমেন্ট দেশের এক নম্বর সিমেন্ট' },
  { name: 'Meghna Cement Mills', cat: 'Cement Mills', yt: 'yT_1q4x_C3T', title: 'Meghna Cement Mills - মেঘনা সিমেন্ট মিলস লিমিটেড' },
  { name: 'KSRM Steel', cat: 'Steel Re-Rolling', yt: 'zU_0p5x_D2U', title: 'KSRM Steel - কেএসআরএম স্টিল টেকসই রড কোয়ালিটি' },
  { name: 'Abul Khair Steel', cat: 'Steel & GCI Sheet', yt: 'aV_9o6x_E1V', title: 'Abul Khair Steel - আবুল খায়ের স্টিল ও শাহ সিমেন্ট' },
  { name: 'PHP Steel', cat: 'Corrugated Steel Sheet', yt: 'bW_8n7x_F0W', title: 'PHP Steel - পিএইচপি টিন ও গলভানাইজড স্টিল' },
  { name: 'Rahim Steel', cat: 'Re-Rolling Mills', yt: 'cX_7m8x_G9X', title: 'Rahim Steel - রহিম স্টিল মেল্টিং ও রিরোলিং' },
  { name: 'Kabir Steel Re-Rolling Mills', cat: 'High Strength Steel', yt: 'dY_6l9x_H8Y', title: 'Kabir Steel (KSRM) - কবির স্টিল ৫০৫এক্সডব্লিউ রড' },
  { name: 'Energypac Power Generation', cat: 'Power & Energy Services', yt: 'eZ_5k0x_I7Z', title: 'Energypac Power - এনার্জিপ্যাক পাওয়ার জেনারেশন সার্ভিস' },
  { name: 'Confidence Power', cat: 'Thermal Power Plant', yt: 'fA_4j1x_J6A', title: 'Confidence Power - কনফিডেন্স পাওয়ার জেনারেটিং স্টেশন' },
  { name: 'Anlima Yarn Dyeing', cat: 'Textile Dyeing', yt: 'gB_3i2x_K5B', title: 'Anlima Yarn Dyeing - আনলিমা ইয়ার্ন ডাইং টেক্সটাইল' },
  { name: 'Square Hospitals', cat: 'Healthcare & Hospitals', yt: 'hC_2h3x_L4C', title: 'Square Hospitals - স্কয়ার হাসপাতাল বিশ্বমানের চিকিৎসা সেবাসমূহে' },
  { name: 'United Hospital', cat: 'Multi-Specialty Hospital', yt: 'iD_1g4x_M3D', title: 'United Hospital - ইউনাইটেড হাসপাতাল কার্ডিয়াক ও ক্রিটিক্যাল কেয়ার' },
  { name: 'Evercare Hospital Bangladesh', cat: 'Super Specialty Hospital', yt: 'jE_0f5x_N2E', title: 'Evercare Hospital - এভারকেয়ার হাসপাতাল জেসিআই স্বীকৃত সেবা' },
  { name: 'Labaid Group', cat: 'Cardiac Hospital & Diagnostics', yt: 'kF_9e6x_O1F', title: 'Labaid Cardiac - ল্যাবএইড কার্ডিয়াক ও ডায়াগনস্টিক সার্ভিস' },
  { name: 'Ibn Sina Trust', cat: 'Hospital & Medical College', yt: 'lG_8d7x_P0G', title: 'Ibn Sina Trust - ইবনে সিনা ডায়াগনস্টিক ও হাসপাতাল' },
  { name: 'Popular Diagnostic Centre', cat: 'Diagnostic & Medical Services', yt: 'mH_7c8x_Q9H', title: 'Popular Diagnostic - পপুলার ডায়াগনস্টিক আধুনিক প্যাথলজি' },
  { name: 'Medinova Medical Services', cat: 'Diagnostic Centre', yt: 'nI_6b9x_R8I', title: 'Medinova Medical - মেডিনোভা মেডিকেল সার্ভিসেস অ্যান্ড ল্যাব' },
  { name: 'Asgar Ali Hospital', cat: 'Specialized Hospital', yt: 'oJ_5a0x_S7J', title: 'Asgar Ali Hospital - আসগর আলী হাসপাতাল পুরান ঢাকা কেয়ার' },
  { name: 'Bangladesh Specialized Hospital', cat: 'Specialized Hospital', yt: 'pK_4z1x_T6K', title: 'Bangladesh Specialized Hospital - বাংলাদেশ স্পেশালাইজড হাসপাতাল' },
  { name: 'Continental Hospital', cat: 'Healthcare Services', yt: 'qL_3y2x_U5L', title: 'Continental Hospital - কন্টিনেন্টাল হাসপাতাল ডায়াগনস্টিক সেবাসমূহ' },
  { name: 'UCB Fintech (Upay)', cat: 'Mobile Financial Services', yt: 'rM_2x3x_V4M', title: 'Upay (UCB Fintech) - উপায় মোবাইল ওয়ালেট ডিজিটাল পেমেন্ট' },
  { name: 'Nagad', cat: 'Digital Financial Service', yt: 'sN_1w4x_W3N', title: 'Nagad (নগদ) - নগদ ডাক বিভাগের ডিজিটাল ফাইন্যান্সিয়াল সার্ভিস' },
  { name: 'Walton Mobile', cat: 'Smartphones & Tech', yt: 'tO_0v5x_X2O', title: 'Walton Mobile - ওয়ালটন অরবিট স্মার্টফোন কমার্শিয়াল' },
  { name: 'Symphony Mobile', cat: 'Smartphones & Gadgets', yt: 'uP_9u6x_Y1P', title: 'Symphony Mobile - সিমফনি স্মার্টফোন মেড ইন বাংলাদেশ' },
  { name: 'Edison Group', cat: 'Telecom & Tech', yt: 'vQ_8t7x_Z0Q', title: 'Edison Group - এডিসন গ্রুপ ও সিমেন্ট অ্যাপ্লায়েন্সেস' },
  { name: 'Otobi Furniture', cat: 'Home & Office Furniture', yt: 'wR_7s8x_A9R', title: 'Otobi Furniture - অটোরি ফার্নিচার আধুনিক ইন্টেরিয়র ডিজাইন' },
  { name: 'HATIL Furniture', cat: 'Luxury Smart Furniture', yt: 'xS_6r9x_B8S', title: 'HATIL Furniture - হাতিলে স্মার্ট ফার্নিচার অ্যান্ড ডেকোর' },
  { name: 'Brothers Furniture', cat: 'Solid Wood Furniture', yt: 'yT_5q0x_C7T', title: 'Brothers Furniture - ব্রাদার্স ফার্নিচার কাঠের আভিজাত্য' },
  { name: 'Regal Furniture', cat: 'RFL Regal Furniture', yt: 'zU_4p1x_D6U', title: 'Regal Furniture - রিগ্যাল ফার্নিচার আধুনিক ডিজাইনের প্রতিশ্রুতি' },
  { name: 'Iskandar Agro', cat: 'Agro & Fisheries', yt: 'aV_3o2x_E5V', title: 'Iskandar Agro - ইসকান্দার এগ্রো ও পোল্ট্রি ফার্মস' },
  { name: 'ACI Motors', cat: 'Agricultural Machinery', yt: 'bW_2n3x_F4W', title: 'ACI Motors - এসিআই মোটরস সোনালিকা ট্রাক্টর' },
  { name: 'Yamaha Bangladesh', cat: 'Motorcycles & Bikes', yt: 'cX_1m4x_G3X', title: 'Yamaha Bangladesh - ইয়ামাহা মেটালিক মোটরসাইকেল কমার্শিয়াল' },
  { name: 'Runner Automobiles', cat: 'Automotive & Bikes', yt: 'dY_0l5x_H2Y', title: 'Runner Automobiles - রানার মোটরসাইকেল বিডি ব্র্যান্ড' },
  { name: 'Uttara Motors (Bajaj)', cat: 'Bajaj Motorcycles', yt: 'eZ_9k6x_I1Z', title: 'Uttara Motors - বাজাজ পালসার ও ডিসকভার মোটরস' },
  { name: 'TVS Auto Bangladesh', cat: 'TVS Motorcycles', yt: 'fA_8j7x_J0A', title: 'TVS Auto BD - টিভিএস অ্যাপাচি আরটিআর মোটরসাইকেল' },
  { name: 'Hero Bangladesh (Niloy)', cat: 'Hero Motorcycles', yt: 'gB_7i8x_K9B', title: 'Hero Bangladesh - হিরো গ্ল্যামার ও স্প্লেন্ডার বাইক টিভিসি' },
  { name: 'Suzuki Bangladesh', cat: 'Suzuki Motorcycles', yt: 'hC_6h9x_L8C', title: 'Suzuki Bangladesh - সুজুকি জিক্সার স্পোর্টস বাইক' },
  { name: 'Grameen Telecom', cat: 'Telecom & Tech', yt: 'iD_5g0x_M7D', title: 'Grameen Telecom - গ্রামীণ টেলিকম সার্ভিসেস অ্যান্ড সোলিউশনস' },
  { name: 'Banglalink Digital', cat: 'Digital Telco', yt: 'jE_4f1x_N6E', title: 'Banglalink Digital - বাংলালিংক ৪জি ফাস্টেস্ট নেটওয়ার্ক' },
  { name: 'Robi Axiata Enterprise', cat: 'B2B ICT Telco', yt: 'kF_3e2x_O5F', title: 'Robi Enterprise - রবি ক্লাউড অ্যান্ড কর্পোরেট কনেক্টিভিটি' },
  { name: 'Shwapno Super Shop', cat: 'Retail Supermarket Chain', yt: 'lG_2d3x_P4G', title: 'Shwapno Super Shop - স্বপ্ন সুপার শপ সেরা গ্রোসারি অফার' },
  { name: 'Meena Bazar', cat: 'Supermarket Chain', yt: 'mH_1c4x_Q3H', title: 'Meena Bazar - মীনাবাজার টাটকা বাজার ও অনলাইন ডেলিভারি' },
  { name: 'Agora Superstore', cat: 'Retail Chain', yt: 'nI_0b5x_R2I', title: 'Agora Superstore - অ্যাগোরা সুপারস্টোর ফ্রেশ গ্রোসারি' },
  { name: 'Unimart', cat: 'Hypermarket Chain', yt: 'oJ_9a6x_S1J', title: 'Unimart - ইউনিমার্ট প্রিমিয়াম হাইপারমার্কেট শপিং' },
  { name: 'Chaldal Bangladesh', cat: 'Online Grocery Delivery', yt: 'pK_8z7x_T0K', title: 'Chaldal - চালডাল অনলাইন গ্রোসারি হোম ডেলিভারি' },
  { name: 'Pathao Ltd.', cat: 'Ride Sharing & Courier', yt: 'qL_7y8x_U9L', title: 'Pathao - পাঠাও রাইড, পার্সেল ও ফুড হোম ডেলিভারি' },
  { name: 'Shohoz', cat: 'Ticketing & Travel App', yt: 'rM_6x9x_V8M', title: 'Shohoz - সহজ বাস, ট্রেন ও ট্রাভেল টিকেট অনলাইন' },
  { name: 'Foodpanda Bangladesh', cat: 'Food & Grocery Delivery', yt: 'sN_5w0x_W7N', title: 'Foodpanda BD - ফুডপান্ডা দ্রুত ফুড ও গ্রোসারি ডেলিভারি' },
  { name: 'Daraz Bangladesh', cat: 'E-Commerce Marketplace', yt: 'tO_4v1x_X6O', title: 'Daraz BD - তারাঝ ১-১১ মেগা শপিং ফেস্টিভাল টিভিসি' },
  { name: 'Evaly', cat: 'E-Commerce Platform', yt: 'uP_3u2x_Y5P', title: 'Evaly - ইভ্যালি মেগা কেনাকাটা ধামাকা অফার' },
  { name: 'Pickaboo', cat: 'Electronics E-Commerce', yt: 'vQ_2t3x_Z4Q', title: 'Pickaboo - পিকাবু ১০০% অরিজিনাল গ্যাজেট শপ' },
  { name: 'ShareTrip', cat: 'Online Travel Agency', yt: 'wR_1s4x_A3R', title: 'ShareTrip - শেয়ারট্রিপ এয়ার টিকেট ও হোটেল বুকিং' },
  { name: 'GoZayaan', cat: 'Travel Tech', yt: 'xS_0r5x_B2S', title: 'GoZayaan - গোজায়ান ট্রাভেল ফ্লাইট বুকিং অ্যাপ' },
  { name: 'SSLCommerz', cat: 'Digital Payment Gateway', yt: 'yT_9q6x_C1T', title: 'SSLCommerz - এসএসএলকমার্স অনলাইন পেমেন্ট গেটওয়ে' },
  { name: 'Shurjopay', cat: 'Fintech Payment Gateway', yt: 'zU_8p7x_D0U', title: 'Shurjopay - সূর্যপে ডিজিটাল মার্চেন্ট পেমেন্ট গেটওয়ে' },
  { name: 'CellFin (Islami Bank)', cat: 'Digital Banking App', yt: 'aV_7o8x_E9V', title: 'CellFin - সেলফিন ইসলামী ব্যাংক ডিজিটাল অ্যাপ' },
  { name: 'Tap (MTB)', cat: 'MFS Wallet', yt: 'bW_6n9x_F8W', title: 'Tap (MTB) - মিউচুয়াল ট্রাস্ট ব্যাংক ট্যাপ মোবাইল ওয়ালেট' },
  { name: 'Pocket (AB Bank)', cat: 'Digital Wallet', yt: 'cX_5m0x_G7X', title: 'Pocket AB Bank - পকেট এবি ব্যাংক ডিজিটাল ওয়ালেট' },
  { name: 'DBBL NexusPay', cat: 'Mobile Payment App', yt: 'dY_4l1x_H6Y', title: 'DBBL NexusPay - ডাচ-বাংলা ব্যাংক নেক্সাসপে কিউআর' },
  { name: 'Citytouch', cat: 'City Bank Digital Banking', yt: 'eZ_3k2x_I5Z', title: 'Citytouch - সিটি ব্যাংক ইন্টারনেটে স্মার্ট ব্যাংকিং' },
  { name: 'EBL SKYBANKING', cat: 'Eastern Bank Digital App', yt: 'fA_2j3x_J4A', title: 'EBL SKYBANKING - ইস্টার্ন ব্যাংক স্কাইব্যাংকিং অ্যাপ' },
  { name: 'Astha (BRAC Bank)', cat: 'Digital Banking App', yt: 'gB_1i4x_K3B', title: 'Astha BRAC Bank - আস্থায় সহজ ব্যাংকিং সেবা' },
  { name: 'TapTap Send BD', cat: 'International Remittance', yt: 'hC_0h5x_L2C', title: 'TapTap Send BD - ট্যাপট্যাপ সেন্ড দিয়ে দ্রুত রেমিট্যান্স' }
];

// Deduplicate by company name to guarantee zero duplicate company names
const seenCompanies = new Set();
const uniqueCompanies = [];

for (const c of companiesList) {
  const normName = c.name.toLowerCase().trim();
  if (!seenCompanies.has(normName)) {
    seenCompanies.add(normName);
    uniqueCompanies.push(c);
  }
}

// Generate unique video objects
const videoList = uniqueCompanies.map((c, i) => ({
  id: `vid-${i + 1}`,
  title: c.title,
  category: c.cat,
  duration: 30,
  reward: 100,
  url: `https://www.youtube.com/embed/${c.yt}`,
  thumbnail: `https://img.youtube.com/vi/${c.yt}/hqdefault.jpg`,
  description: `${c.name}-এর অফিসিয়াল কমার্শিয়াল ভিডিও বিজ্ঞাপনটি ৩০ সেকেন্ড মনোযোগ সহকারে সম্পূর্ণ দেখুন এবং নিশ্চিত ৳১০০ ইনকাম রিওয়ার্ড ওয়ালেটে গ্রহণ করুন।`,
  available: true
}));

console.log(`Total UNIQUE Company Videos generated: ${videoList.length}`);

const dbPath = path.join(process.cwd(), 'db.json');
const serverPath = path.join(process.cwd(), 'server.ts');

if (fs.existsSync(dbPath)) {
  const dbData = JSON.parse(fs.readFileSync(dbPath, 'utf8'));
  dbData.videos = videoList;
  fs.writeFileSync(dbPath, JSON.stringify(dbData, null, 2), 'utf8');
  console.log(`db.json successfully updated with ${videoList.length} unique company videos!`);
}

if (fs.existsSync(serverPath)) {
  let serverCode = fs.readFileSync(serverPath, 'utf8');
  const videosFormatted = JSON.stringify(videoList, null, 4);
  const regex = /videos:\s*\[[\s\S]*?\n  \],/;
  if (regex.test(serverCode)) {
    serverCode = serverCode.replace(regex, `videos: ${videosFormatted},`);
    fs.writeFileSync(serverPath, serverCode, 'utf8');
    console.log(`server.ts successfully updated with ${videoList.length} unique company videos!`);
  }
}
